xlab-steampunk/spotter-action

.github/workflows/test.yml, README.md, action.yml, entrypoint.sh
This PR adds `--no-docs-url` and updates CI integration tests accordingly.
=> Incorporate no_docs_url option and update CI tests

Dockerfile
This change updates the Steampunk Spotter CLI image to point to https://gitlab.com/xlab-steampunk/steampunk-spotter-client/spotter-cli/container_registry/3453459 and tags version to `1.1.1`.
=> Update Spotter CLI Docker image and tag to 1.1.1

Dockerfile
Updating the CLI Docker image to `1.2.0`.
=> Bump CLI Docker image to 1.2.0

.github/workflows/docker.yml, .github/workflows/test.yml, Dockerfile, README.md
These changes do the following:
- update GH Actions runner image to the latest `ubuntu-22.04`;
- update CLI Docker image tag to `1.2.1`;
- update GH Action tests to prefer API token auth instead of username and password;
- document API token auth and polish README.
=> Update CLI to 1.2.1 and use API tokens for auth

.github/workflows/test.yml, Dockerfile, README.md, action.yml, entrypoint.sh
The following PR brings important additions to the current Spotter GH Action.
The changes here are the following:
- use Spotter CLI version [1.2.6](https://pypi.org/project/steampunk-spotter/1.2.6/);
- update action options in `action.yml` and `entrypoint.sh` to follow up the changes in CLI flags (use include- instead of upload-, introduce scan profiles, remove --option ansible_version=x.y);
- support for setting and clearing custom OPA policies written in Rego Language (this is an enterprise feature for now);
- update integration tests to use the latest changes;
- describe the latest changes in README.
=> CLI to 1.2.6 - option renaming, scan profiles, custom policies

.github/workflows/test.yml, Dockerfile, README.md, action.yml, entrypoint.sh
This will update our Spotter GH Action with the following things:
- upgrade Spotter CLI Docker image tag to the one that uses Spotter CLI version [1.2.7](https://pypi.org/project/steampunk-spotter/1.2.6/);
- add new global inputs (endpoint, API token, username, and password) that support global Spotter CLI flags (this will enable setting those values directly with the action and without the need to export env vars in the action pipeline);
- support skipping checks feature;
- update integration tests to explain and use new functionalities;
- update README to explain and use new functionalities.
=> CLI to 1.2.7, input support for global flags and skipping checks

action.yml
There was a bug in the action because of a missing `skip_checks` input from Dockerfile arguments in `action.yml` file. This will resolve the issue and the action should now behave normally.
=> Add missing skip_checks Dockerfile argument to action.yml

Dockerfile
This change will upgrade the Spotter CLI to version `1.2.8`.
=> Bump CLI Docker image tag to 1.2.8

Dockerfile
We just hit a new milestone - [Steampunk Spotter](https://steampunk.si/spotter/) `2.0` is officially out!
This change will upgrade the [Spotter CLI](https://gitlab.com/xlab-steampunk/steampunk-spotter-client/spotter-cli) version to [`2.0.0`](https://pypi.org/project/steampunk-spotter/2.0.0/) for our GitHub Action.
=> Bump Spotter CLI Docker image tag to 2.0.0

.github/workflows/test.yml, Dockerfile, README.md, action.yml, entrypoint.sh, tests/config.yml
The changes here will:
- upgrade Steampunk Spotter CLI to version `2.1.0`;
- support `enforce_checks` and `config` action inputs;
- enhance integration tests according to the changes;
- update README according to the changes.
=> Bump Spotter CLI to 2.1.0 and support enforcing checks and setting config

.github/workflows/docker.yml
These changes will make sure that on every new tag push the `latest` Spotter action Docker image tag from `action.yml ` will be replaced by the tag of the newly created Spotter action Docker image tag.
The CI/CD and the release process now goes like this:
- we update Spotter CLI's Docker image in `Dockerfile` when a new Spotter CLI gets released;
- on a pull request, we should build the Spotter action Docker image with changes and test the action;
- the master branch keeps using the latest Spotter action Docker image tag;
- on the tag branch we build and push a new Spotter action Docker image with the same tag;
- then the latest Spotter Docker image tag from `action.yml` is replaced by the tag of the newly created Docker image tag;     
- after that, the Spotter action is be ready to be …
=> Update Docker image tag from action.yml on tag push

Dockerfile
This will make sure that Spotter GH Action uses the latest Spotter CLI version [`2.2.0`](https://pypi.org/project/steampunk-spotter/2.2.0/).
=> Upgrade Spotter CLI Docker image to version 2.2.0

.github/workflows/docker.yml
After implementing `action.yml` updates on tag push by using [fjogeleit/yaml-update-action](https://github.com/fjogeleit/yaml-update-action) in #16 we still need to fix some of the action inputs so it will work in the right way for us. This includes:
- using the latest stable version `v0.13.1` of the action like we do for other actions;
- use `branch` input instead of `targetBranch` to achieve committing to the tag branch;
- setting `createPR` to `false` explicitly to prevent opening a new PR from `branch` to `targetBranch`;
- seting `quotingType` to `"` because this is the one we use.
=> Fix use of yaml-update-action

.github/workflows/test.yml, Dockerfile, README.md, action.yml, entrypoint.sh
The latest Spotter CLI includes a big change that will allow us to provide better and more results to the user when scanning Ansible playbooks. Metadata and values are now collected and transmitted to the backend by default. The user may opt out of this behavior using `--exclude-metadata` and `--exclude-values`, respectively.
So, the changes here do the following:
- bump Spotter CLI Docker image to the latest version `2.3.0`;
- use `--exclude-values` and `--exclude-metadata` instead of --include flags in `entrypoint.sh`;
- add `exclude_values` and `exclude_metadata` action inputs and remove include_ inputs;
- document the exclude_ inputs in README;
- use exclude_ inputs in integration tests.
=> Make uploading values and metadata opt-out, bump CLI to 2.3.0

Dockerfile, entrypoint.sh
With these changes, we make sure that we use the `--no-color` and `--no-progress` CLI options in `entrypoint.sh`. We also upgraded the Spotter CLI to the latest `2.4.0`.
=> Use --no-progress/color and upgrade Spotter CLI to 2.4.0

.github/workflows/docker.yml, .github/workflows/test.yml
These changes will upgrade versions (to their latest versions) of actions used within our GitHub Actions CI/CD workflow.
This is also needed because our `docker` workflow started [failing](https://github.com/xlab-steampunk/spotter-action/actions/runs/6349934157).
The changes were tested locally with [act](https://github.com/nektos/act).
=> Upgrade action versions in CI/CD

Dockerfile
The changes here will bump the Spotter CLI Docker image to the latest version [`2.5.0`](https://pypi.org/project/steampunk-spotter/2.5.0/).
=> Bump Spotter CLI version to 2.5.0

.github/workflows/test.yml, Dockerfile, README.md, entrypoint.sh
With the following changes, we aim to support the latest Spotter CLI version [`3.0.0`](https://pypi.org/project/steampunk-spotter/3.0.0/):
- build GH Action Docker image from Spotter CLI Docker image with tag `3.0.0`;
- use latest CLI features in `entrypoint.sh`;
- update integration tests to use latest CLI features;
- document action changes for version 3.0.0 in README.
=> Integrate with Spotter CLI version 3.0.0

entrypoint.sh
This will help us determine if scans are coming from the CI/CD pipeline.
=> Use --origin scan command option

.github/workflows/test.yml, Dockerfile, README.md, action.yml, entrypoint.sh
Upgrading Spotter CLI to the version `3.1.1`.
=> Bump Spotter CLI Docker image tag to 3.1.1

Dockerfile, entrypoint.sh
In this MR we:
-  fixed cases where project id was provided but was not read properly. Same goes for config file path.
-  Bumped CLI docker image tag to 3.3.0
=> Bugfix for unused project_id and config inputs
